# Site settings
title: 
header-img: img/home-bg.png
email: timberlakece1@my.palmbeachstate.edu
copyright_name: Cet7504
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Cet7504
learn_profile: Cet7504
email_username: timberlakece1@my.palmbeachstate.edu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
